# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: some-long-number

  ##########################
  ### EMAIL
  ##########################

  # For getting automatic emails when an error occurs
  # exception_recipients: List of all emails that should receive the notification
  # sender_address: Who the notification email will be from
  # email_prefix: What each email should be prefixed with
  exception_notifier:
    exception_recipients: [ "developer@email.com" ]
    sender_address: '"Arc Catalog" <info@nines.org>'
    email_prefix: "[DEV:Catalog] "

  admin:
    email: info@nines.org

  # For setting up email - this example uses sendgrid
  smtp_settings:
    address: "smtp.ucdavis.edu"
    #port: 587
    user_name: 'ssing@ucdavis.edu'
    domain: ucdavis.edu'
    password: 'super-secret'
    authentication: :plain
    return_path: http://example.com
    enable_starttls_auto: false
    xsmtpapi: 'catalog'

  ##########################
  ### Images
  ##########################

  paperclip:
    image_magic_path: '/usr/bin'

  ##########################
  ### Skin
  ##########################

  skin:
    site_name_title: 'DEV:Arc Catalog'

  ##########################
  ### SOLR
  ##########################

  # Where the solr index has been set up
  solr:
    url: "http://localhost:8983/solr"
    core_prefix: "localhost:8983/solr"
    path: "/RAILS-ROOT/estc21/solr/server/"

  folders:
    rdf: "/RAILS-ROOT/estc21/rdf"
    marc: "~/marc"
    ecco: "~/ecco"
    rdf_indexer: "/RAILS-ROOT/estc21/rdf-indexer"
    backups: "~/backups"
    uploaded_data: "~/uploaded_data"
    tasks_send_method: "scp"
    tamu_key: 'private-token'

  production:
    ssh_user: "nines"
    ssh_host: "nines.org"

  ##########################
  ### authentication
  ##########################

  authentication:
    private_token: 'secret-edge-TOKEN!'
    emop_token: 'emop-API-access-token'
    emop_url: http://emop.url

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

##########################
### CAPISTRANO
##########################

capistrano:
  repository: "git@github.com:collex/catalog.git"
  staging:
    user: 'arc'
    ssh_name: 'collex'
    deploy_to: '/home/arc/www/catalog'
  production:
    user: 'arc'
    ssh_name: 'ssh-name-to-login-to-server'
    deploy_to: '/home/arc/www/catalog'
