# encoding: UTF-8
# generated by a rake task in Collex

Archive.delete_all()

archives = [
	{ :typ => "node",:name => "Library Catalogs",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "Journals",:parent_id => "",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "Peer-Reviewed Projects",:parent_id => "",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "The Rossetti Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "facilitates the scholarly study of Dante Gabriel Rossetti, the painter, designer, writer, and translator who was, according to both John Ruskin and Walter Pater, the most important and original artistic force in the second half of the nineteenth century in Great Britain.",
		:image_id => "photos_small/85/original/rossettiArchive.jpg", :handle => "rossetti", :site_url => "http://www.rossettiarchive.org", :thumbnail => "http://www.rossettiarchive.org/css/whitedgrmotto.gif"
	},
	{ :typ => "archive",:name => "UVA Special Collections",:parent_id => "Library Catalogs",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "uva_library", :site_url => "http://www.lib.virginia.edu/small/", :thumbnail => "http://staff.lib.virginia.edu/commpub/resources/new_logos/gif/liblogo_bluetxt.gif	"
	},
	{ :typ => "archive",:name => "Victorian Studies Bibliography",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "victbib", :site_url => "http://www.letrs.indiana.edu/web/v/victbib", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Romanticism on the Net",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ron", :site_url => "http://www.ron.umontreal.ca/", :thumbnail => "http://www.erudit.org/images/ronnines.gif"
	},
	{ :typ => "node",:name => "University of Virginia Press",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Victorian Literature and Culture Series, U of Virginia Press",:parent_id => "University of Virginia Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "UVaPress_VLCS", :site_url => "http://www.upress.virginia.edu/browse/series/victorian.html", :thumbnail => "http://rotunda.upress.virginia.edu/images/UVAP_logo.png"
	},
	{ :typ => "node",:name => "Rotunda Imprint, University of Virginia",:parent_id => "Peer-Reviewed Projects",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Letters of Matthew Arnold",:parent_id => "Rotunda Imprint, University of Virginia",:carousel_include => "1",
		:carousel_description => "Including nearly 4,000 letters, The Letters of Matthew Arnold represents the most comprehensive and assiduously annotated collection of his correspondence available. Published by the Rotunda Imprint of University of Virginia Press.",
		:image_id => "photos_small/93/original/arnoldLetters.jpg", :handle => "rotunda_arnold", :site_url => "http://rotunda.upress.virginia.edu/Arnold/", :thumbnail => "http://rotunda.upress.virginia.edu/images/Rotunda-NINES.png"
	},
	{ :typ => "archive",:name => "Letters of Christina Rossetti",:parent_id => "Rotunda Imprint, University of Virginia",:carousel_include => "1",
		:carousel_description => "Christina Rossetti has come to be considered one of the major poets of the Victorian era.This digital edition incorporates the complete text of the 4-volume print edition, The Letters of Christina Rossetti. Published by the Rotunda Imprint of University of Virginia Press.",
		:image_id => "photos_small/101/original/rossettiLetters.jpg", :handle => "rotunda_c-rossetti", :site_url => "http://rotunda.upress.virginia.edu/crossetti", :thumbnail => "http://rotunda.upress.virginia.edu/images/Rotunda-NINES.png"
	},
	{ :typ => "archive",:name => "The Poetess Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "The Poetess Archive Database now contains a bibliography of over 4,000 entries for works by and about writers working in and against the “poetess tradition,” the extraordinarily popular, but much criticized, flowery poetry written in Britain and America between 1750 and 1900.",
		:image_id => "photos_small/81/original/poetessArchive.jpg", :handle => "poetess", :site_url => "http://unixgen.muohio.edu/~poetess/", :thumbnail => "http://unixgen.muohio.edu/~poetess/works/cupidsm.gif"
	},
	{ :typ => "archive",:name => "The Swinburne Project",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "is a digital collection, or virtual archive, devoted to the life and work of Victorian poet Algernon Charles Swinburne. When complete the project will provide students and scholars with access to all available original works by Swinburne and selected contextual materials.",
		:image_id => "photos_small/213/original/swinburneProject.jpg", :handle => "swinburne", :site_url => "http://swinburnearchive.indiana.edu/swinburne/www/swinburne/", :thumbnail => "http://swinburnearchive.indiana.edu/swinburne/www/swinburne/"
	},
	{ :typ => "archive",:name => "The Ambrose Bierce Project",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "is an online forum and resource for the study of Ambrose Gwinnett Bierce (1842-1914?), the American soldier, topographer, journalist, and writer. The ABP strives to bring together Bierce scholars and students from around the globe.",
		:image_id => "photos_small/153/original/bierce.jpg", :handle => "bierce", :site_url => "http://www.ambrosebierce.org/main.html", :thumbnail => "http://www.personal.psu.edu/faculty/c/a/caw43/bierce/bierceicon.jpg"
	},
	{ :typ => "archive",:name => "British Women Romantic Poets",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "The British Women Romantic Poet's Project is producing an online scholarly archive consisting of E-text editions of poetry by British and Irish women written (not necessarily published) between 1789 and 1832.",
		:image_id => "photos_small/113/original/bwrp.jpg", :handle => "bwrp", :site_url => "http://digital.lib.ucdavis.edu/projects/bwrp/", :thumbnail => "http://digital.lib.ucdavis.edu/images/smlpilk2.jpg"
	},
	{ :typ => "archive",:name => "Charles Chesnutt Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "The goal of The Charles Chesnutt Archive is to make works by and about Chesnutt readily and freely accessible to scholars, students, and general readers. It will continue to grow and change with the goal of providing a comprehensive digital collection of Chesnutt materials.",
		:image_id => "photos_small/97/original/chesnuttArchive.jpg", :handle => "chesnutt", :site_url => "http://www.chesnuttarchive.org", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Collective Biographies of Women",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "is an exhaustive annotated bibliography of the more than 930 books published in English (in Britain, the United States, and elsewhere in the Anglophone world) between 1830 and 1940 that collect three or more women's biographies.",
		:image_id => "photos_small/141/original/cbw.jpg", :handle => "cbw", :site_url => "http://etext.lib.virginia.edu/WomensBios/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Dickinson Virtual Reference Shelf",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "The Dickinson Electronic Archives (DEA) is a website devoted to the study of Emily Dickinson, her writing practices, writings directly influencing her work, and critical and creative writings generated by her work.",
		:image_id => "photos_small/137/original/dickinsonVirtual.jpg", :handle => "dickinson", :site_url => "http://www.emilydickinson.org/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The William Blake Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "A free site on the World Wide Web since 1996, the Blake Archive was conceived as an international public resource that would provide unified access to major works of visual and literary art that are highly disparate, widely dispersed, and often severely restricted as a result of their value, rarity, and extreme fragility.",
		:image_id => "photos_small/89/original/blakeArchive.jpg", :handle => "blake", :site_url => "http://www.blakearchive.org", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The Willa Cather Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => " is an ambitious endeavor to create a rich, useful, and widely-accessible site for the study of Willa Cather's life and writings. The project originated in 1997, and over the years has digitized and published hundreds of thousands of words of Cather-authored texts and Cather scholarship.",
		:image_id => "photos_small/125/original/newCather.jpg", :handle => "cather", :site_url => "http://cather.unl.edu/", :thumbnail => "http://cather.unl.edu/images/ninesthumbnails/mainthumb.jpg"
	},
	{ :typ => "node",:name => "Whitman Archive",:parent_id => "Peer-Reviewed Projects",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Whitman Bibliography",:parent_id => "Whitman Archive",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "whitbib", :site_url => "http://www.whitmanarchive.org/bibliography/", :thumbnail => "http://www.whitmanarchive.org/shared/WWA_logo.gif"
	},
	{ :typ => "archive",:name => "The Walt Whitman Archive",:parent_id => "Whitman Archive",:carousel_include => "1",
		:carousel_description => "is an electronic research and teaching tool that sets out to make Whitman's vast work, for the first time, easily and conveniently accessible to scholars, students, and general readers.",
		:image_id => "photos_small/121/original/WhitmanArchive.jpg", :handle => "whitman", :site_url => "http://www.whitmanarchive.org/", :thumbnail => "http://www.whitmanarchive.org/shared/WWA_logo.gif"
	},
	{ :typ => "node",:name => "Romantic Circles",:parent_id => "Peer-Reviewed Projects",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "Project MUSE",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Project Muse: American Literature",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-al", :site_url => "http://muse.jhu.edu/journals/american_literature/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/alcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: American Literary History",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-alh", :site_url => "http://muse.jhu.edu/journals/american_literary_history/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/alhcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: New Literary History",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-nlh", :site_url => "http://muse.jhu.edu/journals/new_literary_history/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/nlhcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: ELH",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-elh", :site_url => "http://muse.jhu.edu/journals/elh/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/elhcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Journal of American Folklore",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-jaf", :site_url => "http://muse.jhu.edu/journals/journal_of_american_folklore/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/jafcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: The Henry James Review",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-hjr", :site_url => "http://muse.jhu.edu/journals/henry_james_review/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/hjrcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: SEL Studies in English Literature 1500-1900",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-sel", :site_url => "http://muse.jhu.edu/journals/studies_in_english_literature/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/selcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Victorian Poetry",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-vp", :site_url => "http://muse.jhu.edu/journals/victorian_poetry/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/vpcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Legacy",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-leg", :site_url => "http://muse.jhu.edu/journals/legacy/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/legcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: The Emily Dickinson Journal",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-edj", :site_url => "http://muse.jhu.edu/journals/emily_dickinson_journal/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/edjcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Victorian Periodicals Review",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-vpr", :site_url => "http://muse.jhu.edu/journals/vpr/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/vprcoversmall.jpg"
	},
	{ :typ => "archive",:name => "Project MUSE: Journal of Victorian Culture",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-jvc", :site_url => "http://muse.jhu.edu/journals/journal_of_victorian_culture/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/jvccoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: English Literature in Transition 1880-1920",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-elt", :site_url => "http://muse.jhu.edu/journals/english_literature_in_transition/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/eltcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Romanticism",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-rom", :site_url => "http://muse.jhu.edu/journals/romanticism/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/romcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Callaloo",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-cal", :site_url => "http://muse.jhu.edu/journals/callaloo/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/calcoversmall.gif"
	},
	{ :typ => "archive",:name => "Project MUSE: Victorian Studies",:parent_id => "Project MUSE",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "muse-vic", :site_url => "http://muse.jhu.edu/journals/vic/", :thumbnail => "http://muse.jhu.edu/images/journals/coverImages/viccoversmall.gif"
	},
	{ :typ => "archive",:name => "Romanticism and Victorianism on the Net",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ravon", :site_url => "http://www.erudit.org/revue/ravon/", :thumbnail => "http://www.erudit.org/ravon_nines.gif"
	},
	{ :typ => "archive",:name => "Herman Melville's \"Typee\": A Fluid-Text Edition",:parent_id => "Rotunda Imprint, University of Virginia",:carousel_include => "1",
		:carousel_description => "This fluid-text edition of the Typee manuscript showcases Melville’s revision process through several stages of the composition of his first published book, Typee: A Peep at Polynesian Life (1846). ",
		:image_id => "photos_small/117/original/typee.jpg", :handle => "rotunda_typee", :site_url => "http://rotunda.upress.virginia.edu/melville", :thumbnail => "http://rotunda.upress.virginia.edu/images/Rotunda-NINES.png"
	},
	{ :typ => "archive",:name => "The Bancroft Library",:parent_id => "Library Catalogs",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "bancroft", :site_url => "http://bancroft.berkeley.edu/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The Lilly Library",:parent_id => "Library Catalogs",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "lilly", :site_url => "http://www.indiana.edu/~liblilly/index.php", :thumbnail => ""
	},
	{ :typ => "node",:name => "Other Digital Collections",:parent_id => "",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "ProQuest: Nineteenth-Century Fiction",:parent_id => "ProQuest",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "PQCh-NCF", :site_url => "http://collections.chadwyck.com/home/home_c19f.jsp", :thumbnail => "http://lion.chadwyck.co.uk/marketing/images/PQ_logo_nines.gif"
	},
	{ :typ => "archive",:name => "The Lay of the Last Minstrel: A Poem",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "was the first of Walter Scott’s metrical romances and the work that made him famous. The object of this edition is to provide the text as originally published, illustrated with annotations and supplementary documents. ",
		:image_id => "photos_small/157/original/lastMinstrel.jpg", :handle => "Last Minstrel", :site_url => "http://scott-minstrel.cath.vt.edu/index", :thumbnail => ""
	},
	{ :typ => "archive",:name => "ProQuest: Early American Fiction",:parent_id => "ProQuest",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "PQCh-EAF", :site_url => "http://collections.chadwyck.com/home/home_eaf2.jsp", :thumbnail => "http://lion.chadwyck.co.uk/marketing/images/PQ_logo_nines.gif"
	},
	{ :typ => "node",:name => "ProQuest",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Leigh Hunt Online: The Letters",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "This project, run by the University of Iowa Library, will ultimately present digitally all surviving correspondence of Romantic poet, writer, and editor Leigh Hunt (1784-1859).",
		:image_id => "photos_small/105/original/leighhunt.jpg", :handle => "leighhunt", :site_url => "http://digital.lib.uiowa.edu/leighhunt/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "19: Interdisciplinary Studies in the Long Nineteenth Century",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "nineteen", :site_url => "http://www.19.bbk.ac.uk/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "From Goslar to Grasmere",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "examines, in text and context, the year from December 1798-December 1799 and the first year in Grasmere in 1800. Across this period William and Dorothy Wordsworth's lives changed dramatically, and with lasting consequences for both their writing.",
		:image_id => "photos_small/145/original/goslartograsmere.jpg", :handle => "goslartograsmere", :site_url => "http://collections.wordsworth.org.uk/gtog/home.asp?", :thumbnail => "http://collections.wordsworth.org.uk/images/G2G%20project/wordsworth1.jpg"
	},
	{ :typ => "archive",:name => "Scottish Women Poets of the Romantic Period",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "swrp", :site_url => "http://asp6new.alexanderstreet.com/swrp/swrp.index.map.aspx", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "node",:name => "Alexander Street Press",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Irish Women Poets of the Romantic Period",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "iwrp", :site_url => "http://asp6new.alexanderstreet.com/iwrp/iwrp.index.map.aspx", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "archive",:name => "Emily Dickinson's Correspondences",:parent_id => "Rotunda Imprint, University of Virginia",:carousel_include => "1",
		:carousel_description => "Unpublished in book form during her lifetime, the poems of Emily Dickinson were nonetheless shared with those she trusted most—through her letters. This XML-based archive brings together 74 poems and letters from Emily’s correspondence with her sister-in-law and primary confidante, Susan Dickinson.",
		:image_id => "photos_small/133/original/dickson_correspondence.jpg", :handle => "rotunda_dickinson", :site_url => "http://rotunda.upress.virginia.edu/edc/", :thumbnail => "http://rotunda.upress.virginia.edu/images/Rotunda-NINES.png"
	},
	{ :typ => "archive",:name => "Journal of Emily Shore: Revised and Expanded",:parent_id => "Rotunda Imprint, University of Virginia",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "rotunda_emilyshore", :site_url => "http://rotunda.upress.virginia.edu/EmilyShore/", :thumbnail => "http://rotunda.upress.virginia.edu/images/Rotunda-NINES.png"
	},
	{ :typ => "node",:name => "InteLex",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "The Collected Letters of the Wordsworths",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexWordsworth", :site_url => "http://pinfo.nlx.com/collections/129", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "node",:name => "JSTOR",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "NINES Exhibits",:parent_id => "",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "The Collected Letters of Tennyson",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexTennyson", :site_url => "http://pinfo.nlx.com/collections/118", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "Morris Online Edition",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "features a digital edition of The Life and Death of Jason, including sumptuous page images from the 1895 Kelmscott edition. The overall goal of the Morris Online Edition is to provide readable annotated texts of Morris’s poetry and selected prose, prepared in accordance with current scholarly and critical norms.",
		:image_id => "photos_small/209/original/morrisOnline.jpg", :handle => "morrisedition", :site_url => "http://morrisedition.lib.uiowa.edu/index.html", :thumbnail => "http://morrisedition.lib.uiowa.edu/images/republican.jpg"
	},
	{ :typ => "archive",:name => "The Journals of the Lewis and Clark Expedition Online",:parent_id => "Peer-Reviewed Projects",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "lewisandclark", :site_url => "http://lewisandclarkjournals.unl.edu/", :thumbnail => "http://cdrh.unl.edu/projects/thumbs/lewisandclark.jpg "
	},
	{ :typ => "archive",:name => "The Romantic Age",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexRomanticAge", :site_url => "http://pinfo.nlx.com/collections/105", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Complete Works and Letters of Jane Austen",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexAustenWorksLetters", :site_url => "http://pinfo.nlx.com/collections/12", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Journals of Mary Shelley",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexShelleyJournals", :site_url => "http://pinfo.nlx.com/collections/110", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Novels and Selected Works of Mary Shelley",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexShelleyWorks", :site_url => "http://pinfo.nlx.com/collections/109", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Collected Letters of Samuel Taylor Coleridge",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexColeridge", :site_url => "http://pinfo.nlx.com/collections/33 ", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Works of Charles Darwin",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexDarwin", :site_url => "http://pinfo.nlx.com/collections/37", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Complete Works of George Eliot",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexEliot", :site_url => "http://pinfo.nlx.com/collections/46", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "Civil War Letters and Diaries",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "cwld", :site_url => "http://solomon.cwld.alexanderstreet.com/", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "archive",:name => "The Collected Letters of Thomas Hardy",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexHardy", :site_url => "http://pinfo.nlx.com/collections/57", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Early Lectures of Ralph Waldo Emerson",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexEmersonLectures", :site_url => "http://pinfo.nlx.com/collections/51", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Collected Works of Ralph Waldo Emerson",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexEmersonCollectedWorks", :site_url => "http://pinfo.nlx.com/collections/49", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Journals and Miscellaneous Notebooks of Ralph Waldo Emerson",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexEmersonJournals", :site_url => "http://pinfo.nlx.com/collections/50", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Collected Letters of Joanna Baillie",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexBaillieLetters", :site_url => "http://pinfo.nlx.com/collections/18", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Diaries of William Gladstone",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexGladstone", :site_url => "http://pinfo.nlx.com/collections/56", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Letters of Charlotte Brontë",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexBronteLetters", :site_url => "http://pinfo.nlx.com/collections/27", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "English Short Title Catalogue",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "estc", :site_url => "http://estc.bl.uk/F/?func=file&file_name=login-bl-list", :thumbnail => "http://cbsr.ucr.edu/images/estc.jpg"
	},
	{ :typ => "archive",:name => "Wright American Fiction",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "WrightAmFic", :site_url => "http://www.letrs.indiana.edu/cgi/t/text/text-idx?c=wright2;cc=wright2;sid=2fda8248a5b314bdf2fe730e6a46ca2d;tpl=home.tpl", :thumbnail => ""
	},
	{ :typ => "archive",:name => "British Philosophy 1600-1900",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexBritishPhilosophy", :site_url => "http://pinfo.nlx.com/collections/26", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "node",:name => "Library of Congress",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Library of Congress: George Grantham Bain Collection",:parent_id => "Library of Congress",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "locCommonsBain", :site_url => "http://www.flickr.com/people/library_of_congress/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The Letters of Charles Dickens: 1820-1870",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexDickens", :site_url => "http://pinfo.nlx.com/collections/43", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Collected Works of Marx and Engels",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexMarx", :site_url => "http://pinfo.nlx.com/collections/84", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "node",:name => "University of Florida Digital Collections",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Baldwin Library of Children's Literature",:parent_id => "University of Florida Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "uflBaldwin", :site_url => "http://ufdcweb1.uflib.ufl.edu/ufdc/?a=juv", :thumbnail => "http://ufdc.ufl.edu/design/aggregations/juv/images/buttons/coll.gif"
	},
	{ :typ => "archive",:name => "Digital Library of the Caribbean",:parent_id => "University of Florida Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ufldloc", :site_url => "http://ufdcweb1.uflib.ufl.edu/ufdc/?n=dloc&a=dloc1&m=hhh", :thumbnail => "http://ufdc.ufl.edu/design/wordmarks/dloc.gif"
	},
	{ :typ => "archive",:name => "The Romantic Era Redefined",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "romr", :site_url => "http://asp6new.alexanderstreet.com/romr/", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "archive",:name => "Prints and Photographs Division",:parent_id => "Library of Congress",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "locPrints", :site_url => "http://loc.gov/pictures/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The Old Bailey Online",:parent_id => "Other Digital Collections",:carousel_include => "1",
		:carousel_description => "is a fully searchable edition of the largest body of texts detailing the lives of non-elite people ever published, containing 197,745 criminal trials held at London's central criminal court. ",
		:image_id => "photos_small/327/original/oldBailey.jpg", :handle => "oldBailey", :site_url => "http://www.oldbaileyonline.org", :thumbnail => "http://unixgen.muohio.edu/~poetess/obtext/oldBailey.jpg"
	},
	{ :typ => "node",:name => "Victorian Institute Journal",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "The Poetess Archive Journal",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "ECCO",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ECCO", :site_url => "http://gdc.gale.com/products/eighteenth-century-collections-online/?searched=ecco&advsearch=oneword&highlight=ajaxSearch_highlight+ajaxSearch_highlight1# ", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Caribbean Literature",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "cali", :site_url => "http://lit.alexanderstreet.com/cali", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "archive",:name => "The Letters of George Henry Lewes",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexLewes", :site_url => "http://www.nlx.com/collections/131", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Letters and Diaries of John Henry Newman",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexNewman", :site_url => "http://www.nlx.com/collections/88", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Works of William James",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexWilliamJames", :site_url => "http://www.nlx.com/collections/66", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "archive",:name => "The Correspondence of William James",:parent_id => "InteLex",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "intelexWilliamJamesCorrespondence", :site_url => "http://www.nlx.com/collections/67", :thumbnail => "http://pm.nlx.com/xtf/icons/external/intelexlogo.jpg"
	},
	{ :typ => "node",:name => "Adam Matthew Digital",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Victorian Manuscripts from the Henry W. and Albert A. Berg Collection of The New York Public Library ",:parent_id => "Adam Matthew Digital",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "amdlitmanberg", :site_url => "http://www.amdigital.co.uk/collections/Literary-Manuscripts-Berg/Default.aspx", :thumbnail => "http://www.amdigital.co.uk/images/ampdig-logo.gif"
	},
	{ :typ => "node",:name => "New York Public Library",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "node",:name => "NYPL Exhibitions",:parent_id => "New York Public Library",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Before Victoria: Extraordinary Women of the British Romantic Era; A Selection of Images",:parent_id => "NYPL Exhibitions",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "nyplvictoria", :site_url => "http://legacy.www.nypl.org/research/chss/victoria/index.html", :thumbnail => ""
	},
	{ :typ => "archive",:name => "NYPL Digital Gallery",:parent_id => "New York Public Library",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "nypl", :site_url => "http://digitalgallery.nypl.org/nypldigital/index.cfm", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Everyday Life and Women in America, c.1800-1920",:parent_id => "Adam Matthew Digital",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "amdeveryday", :site_url => "http://www.amdigital.co.uk/collections/Everyday-Life/default.aspx?collectionSection=detailed", :thumbnail => "http://www.amdigital.co.uk/images/ampdig-logo.gif"
	},
	{ :typ => "archive",:name => "The Vault at Pfaff's",:parent_id => "Peer-Reviewed Projects",:carousel_include => "1",
		:carousel_description => "Charles Pfaff's beer cellar in lower Manhattan was a magnet for some of the most unconventional and creative individuals of nineteenth-century New York City, including Walt Whitman, poet and actress Adah Isaacs Menken, journalist and social critic Henry Clapp...",
		:image_id => "photos_small/417/original/pfaffs.jpg", :handle => "Pfaffs", :site_url => "http://digital.lib.lehigh.edu/pfaffs/about/welcome/", :thumbnail => "http://digital.lib.lehigh.edu/pfaffs/whitman_pfaffs.jpg"
	},
	{ :typ => "archive",:name => "North American Indian Thought and Culture",:parent_id => "Alexander Street Press",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ibio", :site_url => "http://alexanderstreet.com/products/ibio.htm", :thumbnail => "http://asp6new.alexanderstreet.com/custlogo/asplogo100.jpg"
	},
	{ :typ => "archive",:name => "“What a certainty of instinctive faith I have in heaven, and in the Mama’s living on”: Unpublished letters of Mrs. Gaskell and unpublished Gaskell family letters.",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_218", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Representing \"Great England\" to Qing China in the Age of Free Trade Imperialism",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_232", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "A Scottish Dozen: Uncollected Poems by Marion Bernstein",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_239", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "William Morris on Prostitution: A Letter of August 17, 1885",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_283", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Interview with William Morris",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_296", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Putting Contents on the Table",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_243", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Lettere A Colori: Descrizioni di dipinti nella corrispondenza di Dante Gabriel Rossetti",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_161", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "The Publishing History of Leaves of Grass",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_237", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "D.G. Rossetti’s “The Burden of Nineveh”: Further Excavations",:parent_id => "NINES Exhibits",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "exhibit_NINES_244", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Eighteenth Century Journals",:parent_id => "Adam Matthew Digital",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "amdecj", :site_url => "http://www.amdigital.co.uk/Collections/Eighteenth-Century-Journals-Portal.aspx", :thumbnail => "http://www.amdigital.co.uk/~/media/Images/Site/AMD%20Site%20Logo.ashx"
	},
	{ :typ => "archive",:name => "Victorian Popular Culture",:parent_id => "Adam Matthew Digital",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "amdVPC", :site_url => "http://www.amdigital.co.uk/collections/Victorian-Popular-Culture.aspx", :thumbnail => "http://www.ampltd.co.uk/images/Running-Men.gif"
	},
	{ :typ => "archive",:name => "JSTOR: Studies in English Literature, 1500-1900",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorSEL", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: American Literature",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorAmerLit", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: American Literary History",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorAmerLitHist", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: Nineteenth-Century Fiction",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorNCF", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: Nineteenth Century Literature",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorNCL", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: NOVEL: A Forum on Fiction",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorFOF", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "A Celebration of Women Writers",:parent_id => "University of Pennsylvania",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "penn_celebration", :site_url => "http://digital.library.upenn.edu/women/writers.html", :thumbnail => "http://digital.library.upenn.edu/women/_graphics/celebration-header.gif"
	},
	{ :typ => "node",:name => "University of Pennsylvania",:parent_id => "Other Digital Collections",:carousel_include => "0",
		:carousel_description => "",
		:image_id => ""
	},
	{ :typ => "archive",:name => "Rare Book and Special Collections Division",:parent_id => "Library of Congress",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "locEphemera", :site_url => "http://www.loc.gov/rr/rarebook/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Nineteenth-Century Art Worldwide",:parent_id => "Journals",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ncaw", :site_url => "http://www.19thc-artworldwide.org/", :thumbnail => ""
	},
	{ :typ => "archive",:name => "JSTOR: Trollopian",:parent_id => "JSTOR",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "jstorTrollopian", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Romantic Circles Editions",:parent_id => "Romantic Circles",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "rc_editions", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Romantic Circles Praxis",:parent_id => "Romantic Circles",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "rc_praxis", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Romantic Circles Scholarly Resources",:parent_id => "Romantic Circles",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "rc_resources", :site_url => "", :thumbnail => ""
	},
	{ :typ => "archive",:name => "Nineteenth-Century Serials Edition",:parent_id => "Peer-Reviewed Projects",:carousel_include => "0",
		:carousel_description => "",
		:image_id => "", :handle => "ncse", :site_url => "", :thumbnail => ""
	},
]

archives.each { |archive|
	do_delay = false
	if archive[:parent_id] == ''
		archive[:parent_id] = 0
	else
		parent = Archive.find_by({ name: archive[:parent_id] })
		if parent
			archive[:parent_id] = parent.id
		else
			do_delay = true
			archives.push(archive)
		end
	end

	if do_delay == false
		img = archive[:image_id]
		archive.delete(:image_id)
		rec = Archive.new(archive)
		File.open("#{Rails.root}/../collex/public/#{img}") { |photo_file| rec.carousel_image = photo_file } if img.length > 0
		rec.save
	end
}

