require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ArchivesController do

  def mock_archive(stubs={})
    @mock_archive ||= mock_model(Archive, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all archives as @archives" do
      Archive.stub(:all) { [mock_archive] }
      get :index
      assigns(:archives).should eq([mock_archive])
    end
  end

  describe "GET show" do
    it "assigns the requested archive as @archive" do
      Archive.stub(:find).with("37") { mock_archive }
      get :show, :id => "37"
      assigns(:archive).should be(mock_archive)
    end
  end

  describe "GET new" do
    it "assigns a new archive as @archive" do
      Archive.stub(:new) { mock_archive }
      get :new
      assigns(:archive).should be(mock_archive)
    end
  end

  describe "GET edit" do
    it "assigns the requested archive as @archive" do
      Archive.stub(:find).with("37") { mock_archive }
      get :edit, :id => "37"
      assigns(:archive).should be(mock_archive)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created archive as @archive" do
        Archive.stub(:new).with({'these' => 'params'}) { mock_archive(:save => true) }
        post :create, :archive => {'these' => 'params'}
        assigns(:archive).should be(mock_archive)
      end

      it "redirects to the created archive" do
        Archive.stub(:new) { mock_archive(:save => true) }
        post :create, :archive => {}
        response.should redirect_to(archive_url(mock_archive))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved archive as @archive" do
        Archive.stub(:new).with({'these' => 'params'}) { mock_archive(:save => false) }
        post :create, :archive => {'these' => 'params'}
        assigns(:archive).should be(mock_archive)
      end

      it "re-renders the 'new' template" do
        Archive.stub(:new) { mock_archive(:save => false) }
        post :create, :archive => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested archive" do
        Archive.stub(:find).with("37") { mock_archive }
        mock_archive.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :archive => {'these' => 'params'}
      end

      it "assigns the requested archive as @archive" do
        Archive.stub(:find) { mock_archive(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:archive).should be(mock_archive)
      end

      it "redirects to the archive" do
        Archive.stub(:find) { mock_archive(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(archive_url(mock_archive))
      end
    end

    describe "with invalid params" do
      it "assigns the archive as @archive" do
        Archive.stub(:find) { mock_archive(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:archive).should be(mock_archive)
      end

      it "re-renders the 'edit' template" do
        Archive.stub(:find) { mock_archive(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested archive" do
      Archive.stub(:find).with("37") { mock_archive }
      mock_archive.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the archives list" do
      Archive.stub(:find) { mock_archive }
      delete :destroy, :id => "1"
      response.should redirect_to(archives_url)
    end
  end

end
