require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ExhibitsController do

  def mock_exhibit(stubs={})
    @mock_exhibit ||= mock_model(Exhibit, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all exhibits as @exhibits" do
      Exhibit.stub(:all) { [mock_exhibit] }
      get :index
      assigns(:exhibits).should eq([mock_exhibit])
    end
  end

  describe "GET show" do
    it "assigns the requested exhibit as @exhibit" do
      Exhibit.stub(:find).with("37") { mock_exhibit }
      get :show, :id => "37"
      assigns(:exhibit).should be(mock_exhibit)
    end
  end

  describe "GET new" do
    it "assigns a new exhibit as @exhibit" do
      Exhibit.stub(:new) { mock_exhibit }
      get :new
      assigns(:exhibit).should be(mock_exhibit)
    end
  end

  describe "GET edit" do
    it "assigns the requested exhibit as @exhibit" do
      Exhibit.stub(:find).with("37") { mock_exhibit }
      get :edit, :id => "37"
      assigns(:exhibit).should be(mock_exhibit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created exhibit as @exhibit" do
        Exhibit.stub(:new).with({'these' => 'params'}) { mock_exhibit(:save => true) }
        post :create, :exhibit => {'these' => 'params'}
        assigns(:exhibit).should be(mock_exhibit)
      end

      it "redirects to the created exhibit" do
        Exhibit.stub(:new) { mock_exhibit(:save => true) }
        post :create, :exhibit => {}
        response.should redirect_to(exhibit_url(mock_exhibit))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exhibit as @exhibit" do
        Exhibit.stub(:new).with({'these' => 'params'}) { mock_exhibit(:save => false) }
        post :create, :exhibit => {'these' => 'params'}
        assigns(:exhibit).should be(mock_exhibit)
      end

      it "re-renders the 'new' template" do
        Exhibit.stub(:new) { mock_exhibit(:save => false) }
        post :create, :exhibit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exhibit" do
        Exhibit.stub(:find).with("37") { mock_exhibit }
        mock_exhibit.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :exhibit => {'these' => 'params'}
      end

      it "assigns the requested exhibit as @exhibit" do
        Exhibit.stub(:find) { mock_exhibit(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:exhibit).should be(mock_exhibit)
      end

      it "redirects to the exhibit" do
        Exhibit.stub(:find) { mock_exhibit(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(exhibit_url(mock_exhibit))
      end
    end

    describe "with invalid params" do
      it "assigns the exhibit as @exhibit" do
        Exhibit.stub(:find) { mock_exhibit(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:exhibit).should be(mock_exhibit)
      end

      it "re-renders the 'edit' template" do
        Exhibit.stub(:find) { mock_exhibit(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exhibit" do
      Exhibit.stub(:find).with("37") { mock_exhibit }
      mock_exhibit.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the exhibits list" do
      Exhibit.stub(:find) { mock_exhibit }
      delete :destroy, :id => "1"
      response.should redirect_to(exhibits_url)
    end
  end

end
